[template]
cargo_generate_version = ">=0.23.0"
# Only process substitution in these files; all other files are copied verbatim
include = [
    "Cargo.toml",
    "business/Cargo.toml",
    "infrastructure/Cargo.toml",
    "presentation/Cargo.toml",
    "presentation/src/main.rs.liquid",
]
